### ISSUE TITLE
How can i run this app on linux vps?

### ISSUE THREAD

**Issue by TheCrimsonborn** [Ju0x/discord-richpresence-example#1]
I need run it on the linux but its a normal server and Discord needs to run for the app to work...

**Comment by Ju0x** [comment]
> 
> 
> I need run it on the linux but its a normal server and Discord needs to run for the app to work...

You can only have a custom Rich-Presence with pypresence for the normal discord client. Because pypresence automatically connects the RP with the account which is logged in. Maybe it works but i dont know how it will work without a normal Discord-Desktop-Client. If you need more information, the developer of pypresence maybe can help you: https://github.com/qwertyquerty/pypresence (GitHub site from pypresence) or the docs: https://qwertyquerty.github.io/pypresence/html/index.html

If you need the RP for a bot, you must search how to make presences in your discord-bot-library.
